### ISSUE TITLE
Time Conversion Errors (AM/PM Mix-up After 1PM)

### ISSUE THREAD

**Issue by jsongski** [deichcode/chisv-helper#2]
![image](https://user-images.githubusercontent.com/34401929/117191423-8ad40e80-adae-11eb-92a2-da9b8200a2c5.png)
![image](https://user-images.githubusercontent.com/34401929/117192614-f36fbb00-adaf-11eb-80e6-16e81d26298c.png)
![image](https://user-images.githubusercontent.com/34401929/117192238-78a6a000-adaf-11eb-8946-310c622bf2b2.png)

* Original (JST) times between 1 AM and 12:59 PM are converting to the correct time (but not day of month). 
* However, original times between 1 **PM** and 12:59 **AM** are being treated as if they are 1 **AM** - 12:59 **PM** (i.e., afternoon/night times are being converted as if they are morning/day).

_Possible cause/fix: Might have something to do with interpreting all original times in 24-hour format instead of AM/PM:_ https://stackoverflow.com/questions/15083548/convert-12-hour-hhmm-am-pm-to-24-hour-hhmm/22497471

**Comment by jsongski** [comment]
UPDATE (Release 2):

AM/PM to 24-hr issue fixed:

![image](https://user-images.githubusercontent.com/34401929/117215866-e1504580-adcc-11eb-8adf-908440d8846d.png)
![image](https://user-images.githubusercontent.com/34401929/117215852-dac1ce00-adcc-11eb-867d-4f98fbe6a31e.png)

Date conversion did not work here:
* The start and end times for this task include the date change in the local time zone, so could this be the problem?

![image](https://user-images.githubusercontent.com/34401929/117216321-8e2ac280-adcd-11eb-9466-671b7bdf31f3.png)
![image](https://user-images.githubusercontent.com/34401929/117216343-984cc100-adcd-11eb-913f-771c102aa723.png)

Seems to work when both start and end times are on the same date (for local time zone):

![image](https://user-images.githubusercontent.com/34401929/117216836-5ec88580-adce-11eb-9854-945dee5d0f0f.png)
![image](https://user-images.githubusercontent.com/34401929/117216918-7f90db00-adce-11eb-915f-365a37862db8.png)

**Comment by deichcode** [comment]
@jsongski: If you have the time, it would be great to verify if the [latest release](https://github.com/deichcode/chisv-helper/releases/latest) fixed the problem.

**Comment by jsongski** [comment]
Just checked v1.0.2 and the date change appears to be working now:

![image](https://user-images.githubusercontent.com/34401929/117329864-13ac8200-ae63-11eb-9486-ca619644e951.png)
![image](https://user-images.githubusercontent.com/34401929/117329963-30e15080-ae63-11eb-988c-a4a91ce3af32.png)

**Comment by deichcode** [comment]
I'll close that issue since it looks like it's resolved.
