### ISSUE TITLE
Wrong calculation until reload

### ISSUE THREAD

**Issue by deichcode** [deichcode/chisv-helper#4]
**Current behavior**
In some cases the extension shows wrong times and dates. This can be 'fixed' by reloading the page.

**Expected behavior**
The times and dates are displayed correctly in _always_

**Comment by jsongski** [comment]
I noticed this happening when navigating across multiple pages:
* Example: The times would be correct initially (page 1), but after clicking to the next page, they would not.

This would resolve itself if I reloaded or if I clicked a bid preference for any task on the page. This also seemed to start happening during a period of high traffic, so I don't know if that is related.

**Comment by deichcode** [comment]
For me it looks like that this bug is also fixed (rather unintentional) by https://github.com/deichcode/chisv-helper/releases/tag/1.0.3. Can you verify this and tell me if it looks the same for you.

**Comment by jsongski** [comment]
Using 1.0.4, it looks like it is fixed for me.
